INSERT INTO Country (name, type) VALUES
('Alabama','US_State'),
('Alaska','US_State'),
('Arizona','US_State'),
('Arkansas','US_State'),
('California','US_State'),
('Colorado','US_State'),
('Connecticut','US_State'),
('Delaware','US_State'),
('Florida','US_State'),
('Georgia','US_State'),
('Hawaii','US_State'),
('Idaho','US_State'),
('Illinois','US_State'),
('Indiana','US_State'),
('Iowa','US_State'),
('Kansas','US_State'),
('Kentucky','US_State'),
('Louisiana','US_State'),
('Maine','US_State'),
('Maryland','US_State'),
('Massachusetts','US_State'),
('Michigan','US_State'),
('Minnesota','US_State'),
('Mississippi','US_State'),
('Missouri','US_State'),
('Montana','US_State'),
('Nebraska','US_State'),
('Nevada','US_State'),
('New Hampshire','US_State'),
('New Jersey','US_State'),
('New Mexico','US_State'),
('New York','US_State'),
('North Carolina','US_State'),
('North Dakota','US_State'),
('Ohio','US_State'),
('Oklahoma','US_State'),
('Oregon','US_State'),
('Pennsylvania','US_State'),
('Rhode Island','US_State'),
('South Carolina','US_State'),
('South Dakota','US_State'),
('Tennessee','US_State'),
('Texas','US_State'),
('Utah','US_State'),
('Vermont','US_State'),
('Virginia','US_State'),
('Washington','US_State'),
('West Virginia','US_State'),
('Wisconsin','US_State'),
('Wyoming','US_State');
