
--

INSERT INTO sections (reg_id, section_number, section_title)
VALUES

-- UTAH (need reg_ids from your DB - using title match with bill number in parens)
((SELECT reg_id FROM regulations WHERE title = 'Health Education Amendments (H 121)'), 'H 121', 'Education Use; Education/Training'),
((SELECT reg_id FROM regulations WHERE title = 'Adult Probation and Parole Amendments (H 163)'), 'H 163', 'Judicial Use'),
((SELECT reg_id FROM regulations WHERE title = 'AI in Education (H 168)'), 'H 168', 'Education Use; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Local Land Use Amendments (H 368)'), 'H 368', 'Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'AI Amendments (H 452)'), 'H 452', 'Health Use; Notification; Oversight/Governance; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Automatic License Plate Reader Amendments (H 468)'), 'H 468', 'Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Technical Corrections to the Utah Code (H 496)'), 'H 496', 'Oversight/Governance'),
((SELECT reg_id FROM regulations WHERE title = 'Appropriations Adjustments (S 3)'), 'S 3', 'Appropriations; Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Law Enforcement Usage of AI (S 180)'), 'S 180', 'Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'AI Consumer Protection Amendments (S 226)'), 'S 226', 'Private Sector Use; Notification'),
((SELECT reg_id FROM regulations WHERE title = 'Unauthorized AI Impersonation (S 271)'), 'S 271', 'Private Sector Use; Private Right of Action'),
((SELECT reg_id FROM regulations WHERE title = 'AI Policy Act Repeal Date (S 332)'), 'S 332', 'Oversight/Governance; Government Use; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Landlords Antitrust Lawsuit (SJR 14)'), 'SJR 14', 'Housing; Private Sector Use'),

-- TEXAS (using exact reg_ids from your query results)
(107, 'H 149', 'Private Sector Use; Government Use; Responsible Use; Child Pornography; Oversight/Governance; Provenance; Studies; Health Use'),
(108, 'H 235', 'Criminal Use'),
(109, 'H 366', 'Notification; Elections'),
(110, 'H 418', 'Child Pornography'),
(111, 'H 449', 'Criminal Use'),
(112, 'H 556', 'Elections; Criminal Use'),
(113, 'H 581', 'Child Pornography; Criminal Use'),
(114, 'H 615', 'Criminal Use'),
(115, 'H 641', 'Education Use; Education/Training'),
(116, 'H 1121', 'Criminal Use'),
(117, 'H 1265', 'Health Use; Oversight/Governance; Government Use; Private Sector Use'),
(118, 'H 1405', 'Education Use; Education/Training'),
(119, 'H 1709', 'Private Sector Use; Education/Training; Government Use; Oversight/Governance; Health Use; Responsible Use; Criminal Use'),
(120, 'H 1717', 'Criminal Use; Child Pornography'),
(121, 'H 2298', 'Health Use; Appropriations; Studies; Oversight/Governance'),
(122, 'H 2400', 'Education Use; Education/Training'),
(123, 'H 2491', 'Private Sector Use; Housing'),
(124, 'H 2818', 'Government Use'),
(125, 'H 2831', 'Health Use; Criminal Use; Government Use; Private Sector Use'),
(126, 'H 2874', 'Provenance; Notification'),
(127, 'H 2922', 'Health Use; Audit; Government Use; Private Sector Use'),
(128, 'H 3300', 'Government Use; Studies'),
(129, 'H 3512', 'Government Use'),
(130, 'H 3694', 'Criminal Use; Child Pornography'),
(131, 'H 3755', 'Private Sector Use'),
(132, 'H 3808', 'Studies; Government Use; Oversight/Governance'),
(133, 'H 3950', 'Criminal Use; Notification'),
(134, 'H 4018', 'Health Use; Private Sector Use'),
(135, 'H 4390', 'Education Use; Notification'),
(136, 'H 4437', 'Government Use; Provenance'),
(137, 'H 4448', 'Education Use'),
(138, 'H 4455', 'Health Use; Private Sector Use; Notification'),
(139, 'H 4503', 'Health Use; Private Sector Use'),
(140, 'H 4585', 'Health Use; Private Sector Use'),
(141, 'H 4635', 'Notification; Health Use; Private Sector Use'),
(142, 'H 4908', 'Taxes; Private Sector Use; Energy'),
(143, 'H 4911', 'Child Pornography; Criminal Use'),
(144, 'H 5118', 'Effect on Labor/Employment; Government Use; Private Sector Use'),
(145, 'H 5282', 'Education Use'),
(146, 'H 5469', 'Studies'),
(147, 'H 5496', 'Notification; Private Sector Use'),
(148, 'H 5517', 'Private Sector Use; Criminal Use'),
(149, 'HCR 53', ''),
(150, 'HR 4', 'Government Use; Studies'),
(151, 'HR 131', 'Education Use; Education/Training'),
(152, 'HR 307', ''),
(153, 'HR 313', ''),
(154, 'HR 795', ''),
(155, 'HR 868', ''),
(156, 'HR 1261', ''),
(157, 'HR 1329', 'Education/Training'),
(158, 'HR 1460', 'Energy'),
(159, 'S 20', 'Child Pornography; Criminal Use'),
(160, 'S 228', 'Elections; Criminal Use'),
(161, 'S 382', 'Education Use; Education/Training'),
(162, 'S 441', 'Criminal Use; Notification'),
(163, 'S 442', 'Criminal Use'),
(164, 'S 668', 'Criminal Use; Notification'),
(165, 'S 747', 'Education Use; Criminal Use'),
(166, 'S 815', 'Health Use; Government Use; Private Sector Use'),
(167, 'S 1188', 'Health Use; Government Use; Private Sector Use'),
(168, 'S 1298', 'Education Use; Education/Training'),
(169, 'S 1393', 'Health Use; Private Sector Use'),
(170, 'S 1411', 'Health Use; Responsible Use; Private Sector Use; Provenance'),
(171, 'S 1445', 'Education Use'),
(172, 'S 1621', 'Child Pornography; Criminal Use'),
(173, 'S 1700', 'Government Use'),
(174, 'S 1822', 'Health Use; Private Sector Use'),
(175, 'S 1960', 'Criminal Use; Private Sector Use'),
(176, 'S 1964', 'Government Use; Notification; Impact Assessment'),
(177, 'S 2373', 'Private Sector Use; Criminal Use'),
(178, 'S 2473', 'Effect on Labor/Employment; Government Use'),
(179, 'S 2490', 'Private Sector Use'),
(180, 'S 2567', 'Private Sector Use; Notification'),
(181, 'S 2787', 'Education Use; Education/Training'),
(182, 'S 2795', 'Judicial Use'),
(183, 'S 2966', 'Private Sector Use'),
(184, 'S 2991', 'Effect on Labor/Employment; Notification; Private Sector Use'),
(185, 'SCR 55', ''),
(186, 'SR 32', ''),

-- TENNESSEE (using exact title match since no ambiguity)
((SELECT reg_id FROM regulations WHERE title = 'Criminal Offenses (H 433)'), 'H 433', 'Criminal Use'),
((SELECT reg_id FROM regulations WHERE title = 'Curriculum Education (H 531)'), 'H 531', 'Education Use; Education/Training'),
((SELECT reg_id FROM regulations WHERE title = 'Department of Education (H 545)'), 'H 545', 'Education Use; Education/Training'),
((SELECT reg_id FROM regulations WHERE title = 'Curriculum Education (H 825)'), 'H 825', 'Education Use'),
((SELECT reg_id FROM regulations WHERE title = 'Statutes and Codification (H 849)'), 'H 849', 'Personhood'),
((SELECT reg_id FROM regulations WHERE title = 'Department of Education (H 933)'), 'H 933', 'Education Use'),
((SELECT reg_id FROM regulations WHERE title = 'Boards and Commissions (H 1209)'), 'H 1209', 'Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Consumer Protection (H 1246)'), 'H 1246', 'Criminal Use; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Criminal Offenses Notification (H 1299)'), 'H 1299', 'Criminal Use; Notification'),
((SELECT reg_id FROM regulations WHERE title = 'Insurance Agents and Policies (H 1382)'), 'H 1382', 'Health Use; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Appropriations (H 1409)'), 'H 1409', 'Appropriations; Government Use'),

-- SOUTH DAKOTA
((SELECT reg_id FROM regulations WHERE title = 'Deepfake to Influence an Election (S 164)'), 'S 164', 'Elections; Notification; Criminal Use'),

-- SOUTH CAROLINA
((SELECT reg_id FROM regulations WHERE title = 'Offense of Intentionally Disseminating Intimate Images (H 3058)'), 'H 3058', 'Criminal Use'),
((SELECT reg_id FROM regulations WHERE title = 'Property Right in Use of Individuals Name (H 3404)'), 'H 3404', 'Criminal Use; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Deepfake Media Distribution (H 3517)'), 'H 3517', 'Elections; Notification; Private Right of Action'),

-- RHODE ISLAND
((SELECT reg_id FROM regulations WHERE title = 'AI Accountability Act (H 5123)'), 'H 5123', 'Impact Assessment; Government Use; Oversight/Governance; Notification; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Transparency of Health Insurers (H 5172)'), 'H 5172', 'Health Use; Private Sector Use; Notification'),
((SELECT reg_id FROM regulations WHERE title = 'Clean Air Preservation Act (H 5217)'), 'H 5217', 'Government Use; Criminal Use; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Synthetic Media in Elections (H 5872)'), 'H 5872', 'Elections'),
((SELECT reg_id FROM regulations WHERE title = 'State Life Science Hub Act (H 5985)'), 'H 5985', 'Health Use; Government Use; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Rules of the Senate (S 8)'), 'S 8', 'Government Use; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Use of AI by Health Insurers (S 13)'), 'S 13', 'Health Use; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Regulatory Provisions on AI Act (S 627)'), 'S 627', 'Responsible Use; Private Sector Use; Impact Assessment; Notification'),
((SELECT reg_id FROM regulations WHERE title = 'Deceptive Synthetic Media in Elections (S 816)'), 'S 816', 'Elections; Private Right of Action'),

-- PUERTO RICO
((SELECT reg_id FROM regulations WHERE title = 'Implementation of Artificial Intelligence (H 427)'), 'H 427', 'Education Use; Education/Training'),
((SELECT reg_id FROM regulations WHERE title = 'Innovation and Technology Service (HJR 68)'), 'HJR 68', 'Studies; Government Use');




--

INSERT INTO sections (reg_id, section_number, section_title)
VALUES

-- WYOMING
((SELECT reg_id FROM regulations WHERE title = 'Misleading Synthetic Media (D 149)'), 'D 149', 'Notification; Criminal Use'),
((SELECT reg_id FROM regulations WHERE title = 'General Government Appropriations (H 1)'), 'H 1', 'Education Use; Education/Training; Appropriations'),
((SELECT reg_id FROM regulations WHERE title = 'General Government Appropriations (S 1)'), 'S 1', 'Education Use; Education/Training; Appropriations'),
((SELECT reg_id FROM regulations WHERE title = 'Political Expenditures (SJR 8)'), 'SJR 8', 'Elections'),

-- WISCONSIN
((SELECT reg_id FROM regulations WHERE title = 'Algorithmic Software for Residential Housing (A 142)'), 'A 142', 'Housing; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Judicial Use of AI (A 292)'), 'A 292', 'Judicial Use; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Algorithmic Software for Residential Housing (S 142)'), 'S 142', 'Housing; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Use of Artificial Intelligence in Court Proceedings (S 295)'), 'S 295', 'Judicial Use'),
((SELECT reg_id FROM regulations WHERE title = 'English As the Official State Language (S 357)'), 'S 357', 'Government Use'),

-- WEST VIRGINIA
((SELECT reg_id FROM regulations WHERE title = 'Certified Microgrid Development Program (H 2014)'), 'H 2014', 'Energy; Private Sector Use; Oversight/Governance'),
((SELECT reg_id FROM regulations WHERE title = 'Fourth Amendment Restoration Act (H 2431)'), 'H 2431', 'Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Economic Incentives for Data Centers (H 3137)'), 'H 3137', 'Energy; Taxes; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Task Force on AI (H 3187)'), 'H 3187', 'Government Use; Studies; Education Use; Effect on Labor/Employment; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Ad Valorem Property Valuation (H 3264)'), 'H 3264', 'Energy; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'AI Elective Course (HCR 94)'), 'HCR 94', 'Studies; Education/Training; Education Use'),
((SELECT reg_id FROM regulations WHERE title = 'Preventing Financial Fraud and Scams (HCR 99)'), 'HCR 99', 'Criminal Use; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Crimes Against Chastity Morality and Decency (S 198)'), 'S 198', 'Child Pornography; Criminal Use'),
((SELECT reg_id FROM regulations WHERE title = 'Synthetic Media and AI (S 484)'), 'S 484', 'Notification; Elections'),
((SELECT reg_id FROM regulations WHERE title = 'Computer Science Course Prior to Graduation (S 558)'), 'S 558', 'Education Use; Education/Training'),
((SELECT reg_id FROM regulations WHERE title = 'Economic Incentives for Data Centers (S 583)'), 'S 583', 'Energy; Private Sector Use; Taxes'),
((SELECT reg_id FROM regulations WHERE title = '4th Amendment Restoration Act (S 688)'), 'S 688', 'Government Use; Responsible Use'),
((SELECT reg_id FROM regulations WHERE title = 'Environment and Humans from Geo Engineering Experiments (S 699)'), 'S 699', 'Criminal Use; Private Sector Use; Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Economic Incentives for Data Centers (S 857)'), 'S 857', 'Energy; Taxes'),

-- WASHINGTON
((SELECT reg_id FROM regulations WHERE title = 'Transparency in AI (H 1168)'), 'H 1168', 'Private Sector Use; Oversight/Governance; Notification; Government Use; Provenance'),
((SELECT reg_id FROM regulations WHERE title = 'Fabricated Depictions of Minors (H 1169)'), 'H 1169', 'Child Pornography'),
((SELECT reg_id FROM regulations WHERE title = 'Developed or Modified by AI (H 1170)'), 'H 1170', 'Responsible Use; Notification; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Fiscal Biennium Supplemental Appropriations (H 1197)'), 'H 1197', 'Education Use; Education/Training; Appropriations'),
((SELECT reg_id FROM regulations WHERE title = 'Advanced Nuclear Advisory Commission (H 1249)'), 'H 1249', 'Energy; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Commercial Liftoff for Energy (H 1481)'), 'H 1481', 'Energy; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Prior Authorization Determination Process (H 1566)'), 'H 1566', 'Health Use; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Use of AI in Government (H 1622)'), 'H 1622', 'Effect on Labor/Employment; Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Personal Data Privacy (H 1671)'), 'H 1671', 'Private Sector Use; Notification'),
((SELECT reg_id FROM regulations WHERE title = 'Technology Used by Employers in the Workplace (H 1672)'), 'H 1672', 'Effect on Labor/Employment; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'AI Grant Program (H 1833)'), 'H 1833', 'Appropriations; Effect on Labor/Employment; Oversight/Governance'),
((SELECT reg_id FROM regulations WHERE title = 'Uses of Artificial Intelligence (H 1942)'), 'H 1942', 'Appropriations; Effect on Labor/Employment'),
((SELECT reg_id FROM regulations WHERE title = 'Legal Personhood by a Governmental Entity (H 2029)'), 'H 2029', 'Personhood'),
((SELECT reg_id FROM regulations WHERE title = 'Sexually Explicit Depictions of Minors (S 5094)'), 'S 5094', 'Child Pornography; Criminal Use'),
((SELECT reg_id FROM regulations WHERE title = 'Fabricated Depictions of Minors (S 5105)'), 'S 5105', 'Child Pornography; Criminal Use'),
((SELECT reg_id FROM regulations WHERE title = 'Fiscal Biennium Supplemental Appropriations (S 5166)'), 'S 5166', 'Effect on Labor/Employment'),
((SELECT reg_id FROM regulations WHERE title = 'Prior Authorization Determination Process (S 5395)'), 'S 5395', 'Health Use; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Use of AI in Government (S 5422)'), 'S 5422', 'Effect on Labor/Employment; Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Rental Housing Market (S 5469)'), 'S 5469', 'Housing; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Supplemental Operating Appropriations (S 5810)'), 'S 5810', 'Education Use; Education/Training; Effect on Labor/Employment'),
((SELECT reg_id FROM regulations WHERE title = 'Science Scientific Research (SR 8651)'), 'SR 8651', 'Education Use; Education/Training; Effect on Labor/Employment'),

-- VIRGINIA
((SELECT reg_id FROM regulations WHERE title = 'Budget Bill (H 30)'), 'H 30', 'Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Department of Criminal Justice Services (H 249)'), 'H 249', 'Government Use; Education/Training'),
((SELECT reg_id FROM regulations WHERE title = 'AI Developer Act (H 747)'), 'H 747', 'Private Sector Use; Impact Assessment; Responsible Use; Health Use'),
((SELECT reg_id FROM regulations WHERE title = 'Public Education (H 1051)'), 'H 1051', 'Education/Training'),
((SELECT reg_id FROM regulations WHERE title = 'AI Generated Image (H 1525)'), 'H 1525', 'Criminal Use'),
((SELECT reg_id FROM regulations WHERE title = 'Criminal Justice Risk Assessments (H 1642)'), 'H 1642', 'Government Use; Judicial Use'),
((SELECT reg_id FROM regulations WHERE title = 'Eligible Security Equipment (H 1818)'), 'H 1818', 'Education Use'),
((SELECT reg_id FROM regulations WHERE title = 'Residential Landlord and Tenant Act (H 1870)'), 'H 1870', 'Private Sector Use; Housing'),
((SELECT reg_id FROM regulations WHERE title = 'High Risk AI (H 2046)'), 'H 2046', 'Government Use; Responsible Use; Oversight/Governance'),
((SELECT reg_id FROM regulations WHERE title = 'State Residential Landlord and Tenant Act (H 2047)'), 'H 2047', 'Housing; Private Sector Use; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'High Risk AI (H 2094)'), 'H 2094', 'Private Sector Use; Responsible Use'),
((SELECT reg_id FROM regulations WHERE title = 'Digital Content Authenticity and Transparency Act (H 2121)'), 'H 2121', 'Provenance; Notification; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Consumer Data Protection Act (H 2250)'), 'H 2250', 'Provenance; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Hospital Nursing Home Fees (H 2255)'), 'H 2255', 'Health Use; Private Sector Use; Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Department of Law (H 2268)'), 'H 2268', 'Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Unlawful Dissemination of Intimate Images of Another (H 2288)'), 'H 2288', 'Criminal Use'),
((SELECT reg_id FROM regulations WHERE title = 'Public Education (H 2338)'), 'H 2338', 'Education Use; Education/Training'),
((SELECT reg_id FROM regulations WHERE title = 'Division of Consumer Counsel (H 2411)'), 'H 2411', 'Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Law Enforcement Agencies (H 2433)'), 'H 2433', 'Government Use; Judicial Use'),
((SELECT reg_id FROM regulations WHERE title = 'Government Use Bill (H 2496)'), 'H 2496', 'Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'AI Transparency Act Established (H 2554)'), 'H 2554', 'Private Sector Use; Notification'),
((SELECT reg_id FROM regulations WHERE title = 'Unlawful Dissemination of Intimate Images (H 2654)'), 'H 2654', 'Criminal Use'),
((SELECT reg_id FROM regulations WHERE title = 'Hospital Oversight Fund (H 2662)'), 'H 2662', 'Health Use; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Custodial Interrogations (H 2692)'), 'H 2692', 'Government Use; Judicial Use'),
((SELECT reg_id FROM regulations WHERE title = 'Resolution (HR 506)'), 'HR 506', ''),
((SELECT reg_id FROM regulations WHERE title = 'Resolution (HR 513)'), 'HR 513', ''),
((SELECT reg_id FROM regulations WHERE title = 'Budget Bill (S 30)'), 'S 30', 'Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'AI Technology In Education Study (S 385)'), 'S 385', 'Education Use; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Commission On AI (S 621)'), 'S 621', 'Effect on Labor/Employment; Responsible Use; Oversight/Governance; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Political Campaign Advertisements (S 775)'), 'S 775', 'Elections'),
((SELECT reg_id FROM regulations WHERE title = 'Nursing Homes and Certified Nursing Facilities (S 1152)'), 'S 1152', 'Health Use; Private Sector Use; Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'AI Transparency Act (S 1161)'), 'S 1161', 'Notification; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'High Risk AI (S 1214)'), 'S 1214', 'Government Use; Oversight/Governance; Responsible Use; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Threats Report Against Health Care Providers (S 1260)'), 'S 1260', 'Health Use; Private Sector Use; Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Residential Landlord and Tenant Act (S 1400)'), 'S 1400', 'Private Sector Use; Housing'),
((SELECT reg_id FROM regulations WHERE title = 'Digital Content Authenticity and Transparency Act (S 1417)'), 'S 1417', 'Provenance; Private Sector Use; Notification'),
((SELECT reg_id FROM regulations WHERE title = 'Joint Commission on Technology and Science (SJR 14)'), 'SJR 14', 'Studies; Government Use'),
((SELECT reg_id FROM regulations WHERE title = 'Commendatory Resolution (SJR 309)'), 'SJR 309', ''),
((SELECT reg_id FROM regulations WHERE title = 'General Assembly Bill (H 6001a)'), 'H 6001a', 'Government Use'),

-- VERMONT
((SELECT reg_id FROM regulations WHERE title = 'Consumer Data Privacy (H 208)'), 'H 208', 'Responsible Use; Provenance; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Prohibiting Geoengineering (H 217)'), 'H 217', 'Government Use; Private Sector Use; Criminal Use'),
((SELECT reg_id FROM regulations WHERE title = 'Electronic Monitoring (H 262)'), 'H 262', 'Effect on Labor/Employment; Government Use; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Public Schools (H 318)'), 'H 318', 'Education/Training'),
((SELECT reg_id FROM regulations WHERE title = 'Social Media Platforms (H 365)'), 'H 365', 'Oversight/Governance; Private Sector Use; Responsible Use'),
((SELECT reg_id FROM regulations WHERE title = 'Use of Dynamic Pricing (H 371)'), 'H 371', 'Private Sector Use; Studies'),
((SELECT reg_id FROM regulations WHERE title = 'Use of Artificial Intelligence (H 389)'), 'H 389', 'Housing; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Synthetic Media in Elections (S 23)'), 'S 23', 'Elections; Notification; Private Sector Use'),
((SELECT reg_id FROM regulations WHERE title = 'Government Use Bill (S 133)'), 'S 133', 'Government Use'),

-- UTAH
((SELECT reg_id FROM regulations WHERE title = 'Current Fiscal Year Supplemental Appropriations (H 3)'), 'H 3', 'Appropriations; Oversight/Governance');

