import type { AnalysisResult } from '../types';

const mockResults: Record<string, AnalysisResult> = {
  en: {
    riskLevel: 'medium',
    issues: [
      {
        title: 'Potential Bias in Language',
        description: 'The content contains language that may reflect demographic bias, which could violate fair lending or equal opportunity regulations.',
        severity: 'high',
      },
      {
        title: 'Missing Disclosure Statement',
        description: 'AI-generated content used in customer-facing communications typically requires a disclosure that it was generated by AI.',
        severity: 'medium',
      },
      {
        title: 'Unverified Claims',
        description: 'The content includes statistical claims that are not attributed to a verified source.',
        severity: 'low',
      },
    ],
    recommendations: [
      {
        title: 'Review for Bias',
        description: 'Run the content through a bias detection tool and revise any flagged language to ensure neutrality.',
      },
      {
        title: 'Add AI Disclosure',
        description: 'Append a disclosure statement such as: "This content was generated with the assistance of AI and reviewed by a human."',
      },
      {
        title: 'Cite Sources',
        description: 'Add citations for all statistical claims or remove unverifiable statements.',
      },
    ],
    explanation: 'The submitted content presents a medium compliance risk. While there are no critical violations, the combination of potential bias and missing disclosures could expose the organization to regulatory scrutiny. I recommend addressing the high-severity bias concern first, then adding the required AI disclosure statement.',
  },
  es: {
    riskLevel: 'medium',
    issues: [
      {
        title: 'Posible Sesgo en el Lenguaje',
        description: 'El contenido contiene lenguaje que puede reflejar sesgo demografico, lo cual podria violar regulaciones de igualdad de oportunidades.',
        severity: 'high',
      },
      {
        title: 'Falta de Declaracion de Divulgacion',
        description: 'El contenido generado por IA utilizado en comunicaciones con clientes generalmente requiere una divulgacion de que fue generado por IA.',
        severity: 'medium',
      },
      {
        title: 'Afirmaciones No Verificadas',
        description: 'El contenido incluye afirmaciones estadisticas que no estan atribuidas a una fuente verificada.',
        severity: 'low',
      },
    ],
    recommendations: [
      {
        title: 'Revisar Sesgo',
        description: 'Ejecute el contenido a traves de una herramienta de deteccion de sesgo y revise cualquier lenguaje marcado.',
      },
      {
        title: 'Agregar Divulgacion de IA',
        description: 'Agregue una declaracion como: "Este contenido fue generado con la asistencia de IA y revisado por un humano."',
      },
      {
        title: 'Citar Fuentes',
        description: 'Agregue citas para todas las afirmaciones estadisticas o elimine las declaraciones no verificables.',
      },
    ],
    explanation: 'El contenido enviado presenta un riesgo de cumplimiento medio. Aunque no hay violaciones criticas, la combinacion de posible sesgo y divulgaciones faltantes podria exponer a la organizacion a escrutinio regulatorio. Recomiendo abordar primero el problema de sesgo de alta gravedad.',
  },
};

export function analyzeContent(language: string): Promise<AnalysisResult> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(mockResults[language] || mockResults.en);
    }, 2000);
  });
}
